In [1]:
# Homework 03
# Due Tuesday, February 16th

In [2]:
# 1. Vector manipulation
# Create a vector of zeros of size 10 but have the fifth value be 1.

import numpy as np
a = np.zeros(10)
a[4] = 1

a

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

In [3]:
# 2. Vector range¶
# Create a vector with values ranging from 10 to 49, inclusive.

b = np.linspace(10.0,49.0,40.0)

bb = np.arange(10,50,1)

b, bb

(array([ 10.,  11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,
         21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,
         32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,
         43.,  44.,  45.,  46.,  47.,  48.,  49.]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
        27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
        44, 45, 46, 47, 48, 49]))

In [4]:
# 3. Reverse a vector
# Write a function, reverse(x) which reverses a vector, so that the first element becomes the last element. The API should be
# return a 1D vector with the elements reversed

# Input
# -----
#     x: 1D array

# Output
# ------
#     res: 1D array, with the elements of `x` reversed

# Include this (or an equivalent description) in the function's docstring.

def reverse(x):      
    'Input ---- x:1D array'
    'Output ---- res: 1D array, with the elements of `x` reversed'
    return x[::-1]

x = np.linspace(10.0,20.0,11.0)
y = np.array([1,2,3,4,5,6,7,8])

print(x)
print(y)

reverse(x), reverse(y)

[ 10.  11.  12.  13.  14.  15.  16.  17.  18.  19.  20.]
[1 2 3 4 5 6 7 8]


(array([ 20.,  19.,  18.,  17.,  16.,  15.,  14.,  13.,  12.,  11.,  10.]),
 array([8, 7, 6, 5, 4, 3, 2, 1]))

In [43]:
# 4. Find indices of non-zero elements
# Write a function find_nonzero(x) that finds the indices of non-zero elements, with an API like
# return the indices of non-zero elements of an array.
# Use the function to get out the non-zero elements from an array containing the elements [1,2,0,0,4,0].

def find_nonzero(x):
    '''return the indices of non-zero elements of an array.
            Input:      x:  array
            Output:     indices: array of integer indices'''
    return np.where(x != 0)  # returning values of the array where x does not equal 0

arr = np.array([1, 2, 0, 0, 4, 0])

non = find_nonzero(arr)

print('these are the indices:', non)
print('these are the non-zero elements:', arr[non])

these are the indices: (array([0, 1, 4], dtype=int64),)
these are the non-zero elements: [1 2 4]


In [7]:
# 5. Array with random values
# Create a 3x3x3 array with normally distributed (μ=0,σ=1) random values.

nn = np.random.normal(0, 1, (3,3,3))

nn

array([[[-0.29020353,  0.21744009, -2.00361697],
        [-0.51872436, -0.95835992,  1.92227931],
        [-0.0132468 , -1.13012776,  1.36159579]],

       [[ 1.09876039, -0.72222184, -0.44121732],
        [ 0.09609831,  0.66534186, -2.13031299],
        [-0.22169678,  0.15123558, -0.01774637]],

       [[ 0.04482539, -0.7437662 ,  0.82238108],
        [ 0.81314077,  0.49338016,  0.08404918],
        [-0.0517906 ,  0.7623311 ,  0.901295  ]]])

In [8]:
# 6. Operations on an array with random values
# Create a 10x10 array with random values. 
c = np.random.rand(10, 10)

# Find the minimum value of the 2nd row
imin = c.min(axis=1)[1]

# the maximum value of the 4th column
imax = c.max(axis=0)[3]

print(c)
imin, imax

[[ 0.00420477  0.81153916  0.15487921  0.86316838  0.05953709  0.96219232
   0.75838817  0.73386825  0.37776778  0.04571325]
 [ 0.92988916  0.73385212  0.14145589  0.03896031  0.32777114  0.71896304
   0.43299931  0.43816329  0.80684169  0.89926051]
 [ 0.95872634  0.39484496  0.03220221  0.76875269  0.90733078  0.38589219
   0.28231451  0.40861774  0.33957126  0.47742426]
 [ 0.74839588  0.86092123  0.20696309  0.60242787  0.97113891  0.25844208
   0.48096782  0.77144029  0.30672499  0.57999222]
 [ 0.65676995  0.21023239  0.75631406  0.5025224   0.53830581  0.48803992
   0.27355269  0.11162118  0.26150382  0.78250801]
 [ 0.99464322  0.61725218  0.54499943  0.16988985  0.5515424   0.26832556
   0.89289902  0.65333596  0.42676376  0.18781047]
 [ 0.05410524  0.05020553  0.79196241  0.94648811  0.59892659  0.62734351
   0.78334708  0.21260416  0.20264974  0.23349411]
 [ 0.55381396  0.93742854  0.18763818  0.86867188  0.66955812  0.9293539
   0.89369089  0.39741504  0.43614778  0.02642161]
 

(0.038960312034001854, 0.94648811147361456)

In [9]:
# 7. Vector without end points
# Create a vector of size 10 with values ranging from 0 to 1, both excluded.

d = np.linspace(0,1,12)[1:-1]
print(d.size)
d

10


array([ 0.09090909,  0.18181818,  0.27272727,  0.36363636,  0.45454545,
        0.54545455,  0.63636364,  0.72727273,  0.81818182,  0.90909091])

In [10]:
# 8. Sorted random vector¶
# Create a random vector of size 10, then sort it.

e = np.random.random(10)
print(e) # not sorted... random
e.sort()
e # sorted in order from least to greatest values

[ 0.48676664  0.1802671   0.18868543  0.38404788  0.85919342  0.35718212
  0.38419092  0.96111683  0.05995731  0.16612707]


array([ 0.05995731,  0.16612707,  0.1802671 ,  0.18868543,  0.35718212,
        0.38404788,  0.38419092,  0.48676664,  0.85919342,  0.96111683])

In [99]:
# 9. Test for array equality
# Write a function is_equal(A, B) that compare two arrays A and B and checks to see if they are equal.
# return True if two arrays are the same shape and all the elements are equal.

# The arrays count as equal if they are the same shape and all elements in the array are equal.

def is_equal(x,y):
    '''Inputs:
            A, B:  array
        Output:
            Bool:  True if A and B have the same shape and identical elements.'''
    return np.allclose(x,y) # returns True if two arrays are element-wise equal within a tolerance

# two random arrays of the same dimension that won't be equal most of the time
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# two equivalent arrays of the same dimension that will always be equal
A2 = np.array([[1., 2., 3.,], [4., 5., 6.]])
B2 = np.array([[1., 2., 3.,], [4., 5., 6.]])

# two differnet arrays of the same dimension that will never be equal
A3 = np.array([[1., 2., 3.,], [4., 5., 6.]])
B3 = np.array([[2., 4., 6.,], [8., 10., 12.]])

is_equal(A,B), is_equal(A2,B2), is_equal(A3,B3)


(False, True, False)

In [13]:
# 10. Subtract the row mean from rows of a matrix
# Create a matrix. Then subtract the mean of each row of the matrix from the respective row. 
# Do this without using a loop (that is, using array operations).

f = np.array([[1., 2., 3.,], [4., 5., 6.]]) # my created matrix
g = f - f.mean(axis=1, keepdims=True) # the matrix with the mean of each row subtracted from the respective row.

print(f.mean(axis=1, keepdims=True))

g

[[ 2.]
 [ 5.]]


array([[-1.,  0.,  1.],
       [-1.,  0.,  1.]])

In [14]:
# 11. Multiply arrays
# Multiply an array of dimension (5,5,3) with an array with dimensions (5,5).
# Then multiply an array of dimension (3,5,5) with an array of dimension (5,5).

h = np.random.rand(5,5,3)  # a 3D array using random numbers
i = np.random.rand(5,5)    # a 2D array using random numbers

j = np.random.rand(3,5,5)  # a 3D array using random numbers

sol1 = h * i[:,:,None]     # element-by-element multiplication letting the 2D array act like a 3D array.
sol2 = j * i               # element-by-element multiplication letting the 2D array act like a 3D array.

sol1, sol2

(array([[[ 0.15638613,  0.56388092,  0.54210227],
         [ 0.34154884,  0.49392148,  0.60079489],
         [ 0.21795667,  0.04116795,  0.52398792],
         [ 0.29132878,  0.23038873,  0.19120006],
         [ 0.2394595 ,  0.253802  ,  0.24524452]],
 
        [[ 0.32687678,  0.39958188,  0.58852744],
         [ 0.12018028,  0.28336318,  0.10692098],
         [ 0.5589084 ,  0.11689971,  0.01011951],
         [ 0.21265561,  0.16556612,  0.15931233],
         [ 0.06416214,  0.12170624,  0.24856832]],
 
        [[ 0.35339265,  0.21065922,  0.92552715],
         [ 0.59179041,  0.01879097,  0.12409004],
         [ 0.04594357,  0.64894366,  0.16403984],
         [ 0.12585444,  0.40685379,  0.07258407],
         [ 0.02653562,  0.37123832,  0.21143474]],
 
        [[ 0.57365237,  0.08474595,  0.18723554],
         [ 0.04372997,  0.06677938,  0.15155691],
         [ 0.07784672,  0.09387005,  0.22630008],
         [ 0.21126782,  0.45029608,  0.5031111 ],
         [ 0.1599375 ,  0.44415693,  0.11

In [51]:
# 12. Creating a new array
# Starting with an array
Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
print('Z =', Z)

# Generate an array
# R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]].

# try to call each element (n) of the array and add +1, +2, +3, to each one... and make an array... [[n, n+1, n+2, n+3], ...]

k = [] 
for n in Z:
    if n<12:
        n = np.array([n,n+1,n+2,n+3])
        k.append(n)
        R = np.asarray(k)
    elif n==12 or n==13:
        continue
    else:
        print('R =', R)
type(R)

Z = [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
R = [[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


numpy.ndarray

In [16]:
# 13. Convert from Cartesian to polar coordinates¶
# Write a function cart2polar(xy) which takes in an Nx2 matrix of x, y pairs representing Cartesian coordinates and return
# the locations represented in polar coordinates in the same shape matrix. The API is
# Return equivalent polar coordinates of specified cartesian points.

xy = np.array([[1,2], [3,5], [2,7]])

def cart2pol(x):
    '''Inputs:
            xy: array
            Nx2 array of Cartesian coordinates, with columns x and y respectively.
        Returns:
            rp: array
            Nx2 array of polar coordinates, with columns radius and angle respectively'''
    
    rho = np.sqrt(x[:,0]**2 + x[:,1]**2)
    phi = np.arctan2(x[:,1], x[:,0]) 
    
    return(np.transpose(np.array([rho, phi])))

cart2pol(xy)

array([[ 2.23606798,  1.10714872],
       [ 5.83095189,  1.03037683],
       [ 7.28010989,  1.29249667]])

In [97]:
# 14. Compute and time for loops and array operations.
# Calculate the time it takes to do what we did in class
import time

a = np.arange(1024.0).reshape(4, 8, 16, 2)   # a 4D array using sequential numbers
b = np.random.rand(4, 8, 16, 2)              # a 4D array using random numbers

t_start1 = time.time()

sol = a * b  # element-by-element multiplication. This operation is about as fast as it can be on your computer.

t_stop1 = time.time()

print('{:6.4f} seconds have passed.'.format(t_stop-t_start))

# and the time required for doing the same operation with a series of 4 for loops, one for each dimension of the arrays. 
# Compare the times by calculating a ratio.

t_start2 = time.time()

sol2 = np.empty_like(sol)
for n in range(a.shape[0]):
    for k in range(a.shape[1]):
        for j in range(a.shape[2]):
            for i in range(a.shape[3]):
                sol2[n, k, j, i] = a[n, k, j, i] * b[n, k, j, i]
                
t_stop2 = time.time()
print('{:6.4f} seconds have passed.'.format(t_stop-t_start))

np.allclose(sol, sol2) # checking to see if the two arrays are element-wise equal to some tolerance.

tot1 = t_stop1 - t_start1
tot2 = t_stop2 - t_start2

print(tot1)
print(tot2)

0.0030 seconds have passed.
0.0030 seconds have passed.
0.0
0.0030002593994140625


In [50]:
# 15. Fix the code
# This code needs to be fixed so that it can run properly and pass the assertion test at the bottom. 
# Write out what you changed to make it work and why it needed to be changed.

def calculate(a, b):
    """Do some calculations
    
    Take in two arrays, subtract 1/4 of the [:2,:] elements from the elements themselves.
    Then multiply with array b and return the result.
    
    Inputs:
        a: input array, shape [MxN]
        b: input array, shape [M]
    
    Returns:
        resultant array
    """

    aa = a[:2, :]/4    # added /4 in this line to divide aa by 4.
    # aa /= 4.         # I took this out because it was not actually dividing aa by 4.
    a[:2, :] -= aa

    return a*b
    

a = np.ones((3, 2)) 
b = np.ones(3)*3
res = calculate(a, b[:, None]) # I made the b array 2D so that I could multiply it with the 2D array a.

assert (res == np.array([[ 2.25,  2.25],[ 2.25,  2.25],[ 3., 3.]])).all()

print(res)

[[ 2.25  2.25]
 [ 2.25  2.25]
 [ 3.    3.  ]]


In [33]:
# 16. Calculate components of a vector
# Read in file data/burl1h2010.txt. This file gives a bunch of data from a wind station. In particular, read in the 
# wind direction, WDIR, and wind speed, WSPD. Then, write a function that calculates and returns the u and v components of this 
# wind vector, which point along the x- and y-axes.
# The function should have the following basic functionality:
# Take in vector and return components.

import math
data = np.loadtxt('burl1h2010.txt')

vdir = data[:,5]
vspd = data[:,6]

def wind_vec(vdir, vspd):
    '''Inputs:
        vdir: vector direction in degrees
        vspd: vector magnitude

    Returns:
        u: x component of vector
        v: y component of vector'''

    u = vspd*np.cos(np.radians(vdir))
    v = vspd*np.sin(np.radians(vdir))
    return([u],[v])

wind_vec(vdir, vspd)

([array([ -2.08397511,  -1.96070053,  -2.12119911, ...,  -9.56084447,
         -10.50707636,  -8.83345912])],
 [array([ 2.1580194 ,  3.01921404,  2.52794666, ...,  6.208885  ,
          5.5867116 ,  5.1       ])])

In [87]:
# 17. (Grad) Write and use a class
# Consider one of the data files located in python4geosciences/data/MCH/. Write a class, dataclass, to store some of the 
# information in the file. The class should:
# be initialized with the name of the file (without file type suffix of .cnv2), and the temperature and salinity values 
# found in the file;
# contain a method, salt_mean, which returns the mean of the salinity;
# contain a method, temp_max, which returns the maximum value of the temperature values.
# Notice that there are many data files in this directory. It would be a lot of work to read them all in by hand. 
# Instead, write a loop which loops through the file names, reads in the necessary data, calls dataclass to store the 
# data in a class instance, and adds it to a list of all of the class instances. At the end of your solution, you should 
# have a list of all of the class instances, one for each data file.
# Hint: Check out the package glob for reading in file names with a wild card.


class dataclass(object):
    
    def __init__(self, filename):
        switch = 0
        self.salt = []
        self.temp = []
        self.f = filename
        f = open(filename)
        
        for line in f.readlines():
            if switch == 1:
                self.salt.append(line.split()[5])
                self.temp.append(line.split()[2])
            if line.split()[0] == '*END*' : switch = 1
                
        self.salt = np.asarray(self.salt, dtype = 'float64')
        self.temp = np.asarray(self.temp, dtype = 'float64')
        
    def salt_mean(self):
        saltmean = np.mean(salt)
        return ('salinity =', saltmean)
    
    def temp_max(self):
        tempmax = np.max(temp)
        return ('temperature =', tempmax)
    
import glob
filegroup = glob.glob('../python4geosciences/data/MCH/*.cnv2')
wind = []
for filename in filegroup:
    wind.append(dataclass(filename))
    
print(wind[1].f)
print(wind[1].salt)
print(wind[1].temp)
       

../python4geosciences/data/MCH\m1001c.cnv2
[ 24.4009  24.397   24.3957  24.4029  24.4197  24.4626  24.548   24.6361
  24.6538  24.692   24.7626  24.8009  24.8066]
[ 22.0411  22.0391  22.0399  22.0399  22.0498  22.0663  22.0935  22.1243
  22.1312  22.1469  22.1756  22.1909  22.1937]


In [98]:
# 18. (Grad) Running mean
# Write a function that computes averages using a sliding window over a vector; that is, it should take in a vector and for every 
# element in the vector, compute the average of that point with the N points on either side of the element. N should also be 
# an input parameter, and the function should return the original vector if N=0. The returned vector should be the same size 
# as the input vector.
# Do not use the pandas package or the function convolve; instead, use a loop. Use the following API for your function:

def sliding_mean(vec, N):
    '''Return the running average of a vector, with averaging window of size N.
    Inputs:
        vec: Input vector
        N (int): Averaging window size, or number of elements to include in mean on either side of each element.

    Outputs:
        out: Vector of running-averaged values; same size as vec'''
    
    v = np.zeros((len(vec),))
    if N == 0:
        return vec
    else:
        for z in range(len(vec)):
            v[z] = np.sum(vec[z:(z+N+1)]) + np.sum(vec[(z-N):z])
    return v/(2*N+1)
            
a = np.array([1,2,3,4,5])
b = np.array([1,1,1,1,1]) 

sliding_mean(a,0)
sliding_mean(a,1)

sliding_mean(b,0)
sliding_mean(b,1)

array([ 0.66666667,  1.        ,  1.        ,  1.        ,  0.66666667])