In [ ]:
# Homework 03
# Due Tuesday, February 16th

In [2]:
# 1. Vector manipulation
# Create a vector of zeros of size 10 but have the fifth value be 1.

import numpy as np
a = np.zeros(10)
a[4] = 1

a

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

In [65]:
# 2. Vector range¶
# Create a vector with values ranging from 10 to 49, inclusive.

# import numpy as np
b = np.linspace(10.0,49.0,40.0)

b

array([ 10.,  11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,
        21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,
        32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,
        43.,  44.,  45.,  46.,  47.,  48.,  49.])

In [20]:
# 3. Reverse a vector
# Write a function, reverse(x) which reverses a vector, so that the first element becomes the last element. The API should be
# return a 1D vector with the elements reversed

# Input
# -----
#     x: 1D array

# Output
# ------
#     res: 1D array, with the elements of `x` reversed

# Include this (or an equivalent description) in the function's docstring.

def reverse(x):      
    'Input ---- x:1D array'
    'Output ---- res: 1D array, with the elements of `x` reversed'
    return x[::-1]

x = np.linspace(10.0,20.0,11.0)
print(x)

reverse(x)

[ 10.  11.  12.  13.  14.  15.  16.  17.  18.  19.  20.]


array([ 20.,  19.,  18.,  17.,  16.,  15.,  14.,  13.,  12.,  11.,  10.])

In [19]:
# 4. Find indices of non-zero elements
# Write a function find_nonzero(x) that finds the indices of non-zero elements, with an API like
# return the indices of non-zero elements of an array.

# Input:      x:  array
# Output:     indices: array of integer indices

# Use the function to get out the non-zero elements from an array containing the elements [1,2,0,0,4,0].

def find_nonzero(x):
    return np.where(x != 0)  # returning values of the array where x does not equal 0

arr = np.array([1, 2, 0, 0, 4, 0])

find_nonzero(arr)

(array([0, 1, 4], dtype=int64),)

In [66]:
# 5. Array with random values
# Create a 3x3x3 array with normally distributed (μ=0,σ=1) random values.

b = np.random.rand(3, 3, 3)
b

# don't know if this is "nornally distributed (μ=0,σ=1)" ???

array([[[ 0.85949755,  0.50163451,  0.36799054],
        [ 0.56078998,  0.77158686,  0.99153137],
        [ 0.72056668,  0.08256487,  0.16112395]],

       [[ 0.1754891 ,  0.40181106,  0.38978535],
        [ 0.91560568,  0.28877823,  0.50514033],
        [ 0.42208246,  0.39174312,  0.5971212 ]],

       [[ 0.57438191,  0.88652111,  0.75484134],
        [ 0.27390853,  0.18556743,  0.88882429],
        [ 0.16215509,  0.25888253,  0.04330334]]])

In [9]:
# 6. Operations on an array with random values
# Create a 10x10 array with random values. 
c = np.random.rand(10, 10)

# Find the minimum value of the 2nd row
imin = c.argmin(axis=1)
print(imin, c.min()) # location of the minimum value for each row, min value for the entire array

# the maximum value of the 4th column
imax = c.argmax(axis=1)
print(imax, c.max()) #  c[imax]??

# how do you find the min/max of a certain row... not the location or array min/max??

[7 9 1 0 6 8 1 4 6 4] 0.00246405371103
[8 0 3 8 0 2 4 8 4 5] 0.980126891611


In [11]:
# 7. Vector without end points
# Create a vector of size 10 with values ranging from 0 to 1, both excluded.

d = np.linspace(0,1,12,endpoint=True)[1:-1]
print(d) # do I need d to be in the output?
d.size

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


10

In [69]:
# 8. Sorted random vector¶
# Create a random vector of size 10, then sort it.

e = np.random.random(10)
print(e) # not sorted... random
e.sort()
e # sorted in order from least to greatest values

[ 0.94267564  0.82707361  0.29878204  0.03286183  0.14090185  0.04601242
  0.20492515  0.4502312   0.76524838  0.28621826]


array([ 0.03286183,  0.04601242,  0.14090185,  0.20492515,  0.28621826,
        0.29878204,  0.4502312 ,  0.76524838,  0.82707361,  0.94267564])

In [25]:
# 9. Test for array equality
# Write a function is_equal(A, B) that compare two arrays A and B and checks to see if they are equal.
# return True if two arrays are the same shape and all the elements are equal.

# Inputs:
#     A, B:  array
# Output:
#     Bool:  True if A and B have the same shape and identical elements.

# The arrays count as equal if they are the same shape and all elements in the array are equal.

def is_equal(x,y):
    return np.allclose(x,y)

# two random arrays of the same dimension that won't be equal most of the time
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# two equivalent arrays of the same dimension that will always be equal
A2 = np.array([[1., 2., 3.,], [4., 5., 6.]])
B2 = np.array([[1., 2., 3.,], [4., 5., 6.]])

# two differnet arrays of the same dimension that will never be equal
A3 = np.array([[1., 2., 3.,], [4., 5., 6.]])
B3 = np.array([[2., 4., 6.,], [8., 10., 12.]])

is_equal(A,B), is_equal(A2,B2), is_equal(A3,B3)

(False, True, False)

In [50]:
# 10. Subtract the row mean from rows of a matrix
# Create a matrix. Then subtract the mean of each row of the matrix from the respective row. 
# Do this without using a loop (that is, using array operations).

f = np.array([[1., 2., 3.,], [4., 5., 6.]]) # my created matrix
g = f - f.mean(axis=1, keepdims=True) # the matrix with the mean of each row subtracted from the respective row.
                                        # how does "f.mean(axis=1, keepdims=True)" work??

print(f.mean(axis=1, keepdims=True))

g

[[ 2.]
 [ 5.]]


array([[-1.,  0.,  1.],
       [-1.,  0.,  1.]])

In [27]:
# 11. Multiply arrays
# Multiply an array of dimension (5,5,3) with an array with dimensions (5,5).
# Then multiply an array of dimension (3,5,5) with an array of dimension (5,5).

h = np.random.rand(5,5,3)  # a 3D array using random numbers
i = np.random.rand(5,5)    # a 2D array using random numbers

j = np.random.rand(3,5,5)  # a 3D array using random numbers

sol1 = h * i[:,:,None]      # element-by-element multiplication letting the 2D array act like a 3D array.
sol2 = j * i[None,:,:]      # element-by-element multiplication letting the 2D array act like a 3D array.

sol1, sol2

(array([[[ 0.29266333,  0.0035441 ,  0.17392323],
         [ 0.09954094,  0.03087895,  0.05428363],
         [ 0.31980335,  0.11778372,  0.65776674],
         [ 0.59417137,  0.18674247,  0.29936841],
         [ 0.50737304,  0.24848907,  0.02974263]],
 
        [[ 0.2100599 ,  0.15566047,  0.37771072],
         [ 0.02992649,  0.0312235 ,  0.00302219],
         [ 0.05880916,  0.01420086,  0.13435405],
         [ 0.02889257,  0.06682736,  0.27674769],
         [ 0.79398686,  0.87457126,  0.34721088]],
 
        [[ 0.14489302,  0.14357576,  0.40770076],
         [ 0.20119033,  0.30361443,  0.43509519],
         [ 0.33251004,  0.22003558,  0.01730321],
         [ 0.16418863,  0.34276481,  0.37973792],
         [ 0.04391276,  0.02266859,  0.27949693]],
 
        [[ 0.20389196,  0.26130652,  0.4115689 ],
         [ 0.28684453,  0.25401209,  0.2403504 ],
         [ 0.01129306,  0.04279271,  0.08209507],
         [ 0.18617915,  0.05912299,  0.02844793],
         [ 0.06363839,  0.1344771 ,  0.03

In [28]:
# 12. Creating a new array
# Starting with an array
Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
Z

# Generate an array
# R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]].


# ????



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
# 13. Convert from Cartesian to polar coordinates¶
# Write a function cart2polar(xy) which takes in an Nx2 matrix of x, y pairs representing Cartesian coordinates and return
# the locations represented in polar coordinates in the same shape matrix. The API is
# Return equivalent polar coordinates of specified cartesian points.

# Inputs:
#     xy: array
#          Nx2 array of Cartesian coordinates, with columns x and y respectively.
# Returns:
#     rp: array
#         Nx2 array of polar coordinates, with columns radius and angle respectively
xy = np.array([[1,2], [3,5], [2,7]])

# defining function coverting cartesian coordinates to polar... point by point...
# def cart2pol(x, y):
#     rho = np.sqrt(x**2 + y**2)
#     phi = np.arctan2(y, x)
#     return(rho, phi)

# trying to do that calling x and y values from an array...
def cart2pol(x):
    rho = np.sqrt(x[:, None]**2 + x[None,:]**2)
    phi = np.arctan2(x[None,:], x[:,None]) # why can't we divide here?
    return(np.array([rho, phi]))

cart2pol(xy) # this gives me multiple arrays...???


#???

array([[[[ 1.41421356,  2.82842712],
         [ 3.16227766,  5.38516481],
         [ 2.23606798,  7.28010989]],

        [[ 3.16227766,  5.38516481],
         [ 4.24264069,  7.07106781],
         [ 3.60555128,  8.60232527]],

        [[ 2.23606798,  7.28010989],
         [ 3.60555128,  8.60232527],
         [ 2.82842712,  9.89949494]]],


       [[[ 0.78539816,  0.78539816],
         [ 1.24904577,  1.19028995],
         [ 1.10714872,  1.29249667]],

        [[ 0.32175055,  0.38050638],
         [ 0.78539816,  0.78539816],
         [ 0.5880026 ,  0.95054684]],

        [[ 0.46364761,  0.27829966],
         [ 0.98279372,  0.62024949],
         [ 0.78539816,  0.78539816]]]])

In [ ]:
# 14. Compute and time for loops and array operations.
# Calculate the time it takes to do what we did in class
# a = np.arange(1024.0).reshape(4, 8, 16, 2)   # a 4D array using sequential numbers
# b = np.random.rand(4, 8, 16, 2)              # a 4D array using random numbers
# sol = a * b  # element-by-element multiplication. This operation is about as fast as it can be on your computer.

# and the time required for doing the same operation with a series of 4 for loops, one for each dimension of the arrays. 
# Compare the times by calculating a ratio.

In [45]:
# 15. Fix the code
# This code needs to be fixed so that it can run properly and pass the assertion test at the bottom. 
# Write out what you changed to make it work and why it needed to be changed.

def calculate(a, b):
    """Do some calculations
    
    Take in two arrays, subtract 1/4 of the [:2,:] elements from the elements themselves.
    Then multiply with array b and return the result.
    
    Inputs:
        a: input array, shape [MxN]
        b: input array, shape [M]
    
    Returns:
        resultant array
    """

    aa = a[:2, :]
    aa /= 4.
    a[:2, :] -= aa

    return a*b
    

a = np.ones((3, 2)) 
b = np.ones(3)*3
res = calculate(a, b[:, None]) # I made the b array 2D so that I could multiply it with the 2D array a.

assert (res == np.array([[ 2.25,  2.25],[ 2.25,  2.25],[ 3., 3.]])).all()

# what does this asserstion error even mean?? What 'makes it true'???

AssertionError: 

In [41]:
b

array([ 3.,  3.,  3.])

In [ ]:
# 16. Calculate components of a vector
# Read in file data/burl1h2010.txt. This file gives a bunch of data from a wind station. In particular, read in the 
# wind direction, WDIR, and wind speed, WSPD. Then, write a function that calculates and returns the u and v components of this 
# wind vector, which point along the x- and y-axes.
# The function should have the following basic functionality:
# Take in vector and return components.

# Inputs:
#     vdir: vector direction in degrees
#     vspd: vector magnitude

# Returns:
#     u: x component of vector
#     v: y component of vector

In [ ]:
# 17. (Grad) Write and use a class
# Consider one of the data files located in python4geosciences/data/MCH/. Write a class, dataclass, to store some of the 
# information in the file. The class should:
# be initialized with the name of the file (without file type suffix of .cnv2), and the temperature and salinity values 
# found in the file;
# contain a method, salt_mean, which returns the mean of the salinity;
# contain a method, temp_max, which returns the maximum value of the temperature values.
# Notice that there are many data files in this directory. It would be a lot of work to read them all in by hand. 
# Instead, write a loop which loops through the file names, reads in the necessary data, calls dataclass to store the 
# data in a class instance, and adds it to a list of all of the class instances. At the end of your solution, you should 
# have a list of all of the class instances, one for each data file.
# Hint: Check out the package glob for reading in file names with a wild card.

In [ ]:
# 18. (Grad) Running mean
# Write a function that computes averages using a sliding window over a vector; that is, it should take in a vector and for every 
# element in the vector, compute the average of that point with the N points on either side of the element. N should also be 
# an input parameter, and the function should return the original vector if N=0. The returned vector should be the same size 
# as the input vector.
# Do not use the pandas package or the function convolve; instead, use a loop. Use the following API for your function:
# Return the running average of a vector, with averaging window of size N.

# Inputs:
#     vec: Input vector
#     N (int): Averaging window size, or number of elements to include in mean on either side of each element.

# Outputs:
#     out: Vector of running-averaged values; same size as vec