In [ ]:
# Homework 03
# Due Tuesday, February 16th

In [3]:
# 1. Vector manipulation
# Create a vector of zeros of size 10 but have the fifth value be 1.

import numpy as np
a = np.zeros(10)
a[4] = 1

print(a)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


In [14]:
# 2. Vector range¶
# Create a vector with values ranging from 10 to 49, inclusive.

import numpy as np
b = np.linspace(10.0,49.0,40.0)

print(b)

[ 10.  11.  12.  13.  14.  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.
  25.  26.  27.  28.  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.
  40.  41.  42.  43.  44.  45.  46.  47.  48.  49.]


In [20]:
# 3. Reverse a vector
# Write a function, reverse(x) which reverses a vector, so that the first element becomes the last element. The API should be
# return a 1D vector with the elements reversed

# Input
# -----
#     x: 1D array

# Output
# ------
#     res: 1D array, with the elements of `x` reversed

# Include this (or an equivalent description) in the function's docstring.

def reverse(x):      
    'Input ---- x:1D array'
    'Output ---- res: 1D array, with the elements of `x` reversed'
    return x[::-1]

x = np.linspace(10.0,20.0,11.0)
print(x)

reverse(x)

[ 10.  11.  12.  13.  14.  15.  16.  17.  18.  19.  20.]


array([ 20.,  19.,  18.,  17.,  16.,  15.,  14.,  13.,  12.,  11.,  10.])

In [ ]:
# 4. Find indices of non-zero elements
# Write a function find_nonzero(x) that finds the indices of non-zero elements, with an API like
# return the indices of non-zero elements of an array.

# Input:      x:  array
# Output:     indices: array of integer indices

# Use the function to get out the non-zero elements from an array containing the elements [1,2,0,0,4,0].



In [ ]:
# 5. Array with random values
# Create a 3x3x3 array with normally distributed (μ=0,σ=1) random values.

In [ ]:
# 6. Operations on an array with random values
# Create a 10x10 array with random values. Find
# the minimum value of the 2nd row
# the maximum value of the 4th column

In [ ]:
# 7. Vector without end points
# Create a vector of size 10 with values ranging from 0 to 1, both excluded.

In [ ]:
# 8. Sorted random vector¶
# Create a random vector of size 10, then sort it.

In [ ]:
# 9. Test for array equality
# Write a function is_equal(A, B) that compare two arrays A and B and checks to see if they are equal.
# return True if two arrays are the same shape and all the elements are equal.

# Inputs:
#     A, B:  array
# Output:
#     Bool:  True if A and B have the same shape and identical elements.

# The arrays count as equal if they are the same shape and all elements in the array are equal.

In [ ]:
# 10. Subtract the row mean from rows of a matrix
# Create a matrix. Then subtract the mean of each row of the matrix from the respective row. 
# Do this without using a loop (that is, using array operations).

In [ ]:
# 11. Multiply arrays
# Multiply an array of dimension (5,5,3) with an array with dimensions (5,5). 
# Then multiply an array of dimension (3,5,5) with an array of dimension (5,5).

In [ ]:
# 12. Creating a new array
# Starting with an array
# Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14].

# Generate an array
# R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]].

In [ ]:
# 13. Convert from Cartesian to polar coordinates¶
# Write a function cart2polar(xy) which takes in an Nx2 matrix of x, y pairs representing Cartesian coordinates and return the locations represented in polar coordinates in the same shape matrix. The API is
# Return equivalent polar coordinates of specified cartesian points.

# Inputs:
#     xy: array
#          Nx2 array of Cartesian coordinates, with columns x and y respectively.

# Returns:
#     rp: array
#         Nx2 array of polar coordinates, with columns radius and angle respectively

In [ ]:
# 14. Compute and time for loops and array operations.
# Calculate the time it takes to do what we did in class
# a = np.arange(1024.0).reshape(4, 8, 16, 2)   # a 4D array using sequential numbers
# b = np.random.rand(4, 8, 16, 2)              # a 4D array using random numbers
# sol = a * b  # element-by-element multiplication. This operation is about as fast as it can be on your computer.

# and the time required for doing the same operation with a series of 4 for loops, one for each dimension of the arrays. 
# Compare the times by calculating a ratio.

In [ ]:
# 15. Fix the code
# This code needs to be fixed so that it can run properly and pass the assertion test at the bottom. 
# Write out what you changed to make it work and why it needed to be changed.

def calculate(a, b):
    """Do some calculations
    
    Take in two arrays, subtract 1/4 of the [:2,:] elements from the elements themselves.
    Then multiply with array b and return the result.
    
    Inputs:
        a: input array, shape [MxN]
        b: input array, shape [M]
    
    Returns:
        resultant array
    """

    aa = a[:2, :]
    aa /= 4.
    a[:2, :] -= aa

    return a*b
    

a = np.ones((3, 2))
b = np.ones(3)*3
res = calculate(a, b)

assert (res == np.array([[ 2.25,  2.25],[ 2.25,  2.25],[ 3., 3.]])).all()

In [ ]:
# 16. Calculate components of a vector
# Read in file data/burl1h2010.txt. This file gives a bunch of data from a wind station. In particular, read in the wind direction, WDIR, and wind speed, WSPD. Then, write a function that calculates and returns the u and v components of this wind vector, which point along the x- and y-axes.
# The function should have the following basic functionality:
# Take in vector and return components.

# Inputs:
#     vdir: vector direction in degrees
#     vspd: vector magnitude

# Returns:
#     u: x component of vector
#     v: y component of vector

In [ ]:
# 17. (Grad) Write and use a class
# Consider one of the data files located in python4geosciences/data/MCH/. Write a class, dataclass, to store some of the 
# information in the file. The class should:
# be initialized with the name of the file (without file type suffix of .cnv2), and the temperature and salinity values 
# found in the file;
# contain a method, salt_mean, which returns the mean of the salinity;
# contain a method, temp_max, which returns the maximum value of the temperature values.
# Notice that there are many data files in this directory. It would be a lot of work to read them all in by hand. 
# Instead, write a loop which loops through the file names, reads in the necessary data, calls dataclass to store the 
# data in a class instance, and adds it to a list of all of the class instances. At the end of your solution, you should 
# have a list of all of the class instances, one for each data file.
# Hint: Check out the package glob for reading in file names with a wild card.

In [ ]:
# 18. (Grad) Running mean
# Write a function that computes averages using a sliding window over a vector; that is, it should take in a vector and for every element in the vector, compute the average of that point with the N points on either side of the element. N should also be an input parameter, and the function should return the original vector if N=0. The returned vector should be the same size as the input vector.
# Do not use the pandas package or the function convolve; instead, use a loop. Use the following API for your function:
# Return the running average of a vector, with averaging window of size N.

# Inputs:
#     vec: Input vector
#     N (int): Averaging window size, or number of elements to include in mean on either side of each element.

# Outputs:
#     out: Vector of running-averaged values; same size as vec