In [1]:
# Homework 03
# Due Tuesday, February 16th

In [2]:
# 1. Vector manipulation
# Create a vector of zeros of size 10 but have the fifth value be 1.

import numpy as np
a = np.zeros(10)
a[4] = 1

a

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

In [18]:
# 2. Vector range¶
# Create a vector with values ranging from 10 to 49, inclusive.

b = np.linspace(10.0,49.0,40.0)

bb = np.arange(10,50,1)

b, bb

(array([ 10.,  11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,
         21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,
         32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,
         43.,  44.,  45.,  46.,  47.,  48.,  49.]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
        27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
        44, 45, 46, 47, 48, 49]))

In [49]:
# 3. Reverse a vector
# Write a function, reverse(x) which reverses a vector, so that the first element becomes the last element. The API should be
# return a 1D vector with the elements reversed

# Input
# -----
#     x: 1D array

# Output
# ------
#     res: 1D array, with the elements of `x` reversed

# Include this (or an equivalent description) in the function's docstring.

def reverse(x):      
    'Input ---- x:1D array'
    'Output ---- res: 1D array, with the elements of `x` reversed'
    return x[::-1]

x = np.linspace(10.0,20.0,11.0)
y = np.array([1,2,3,4,5,6,7,8])

print(x)
print(y)

reverse(x), reverse(y)

[ 10.  11.  12.  13.  14.  15.  16.  17.  18.  19.  20.]
[1 2 3 4 5 6 7 8]


(array([ 20.,  19.,  18.,  17.,  16.,  15.,  14.,  13.,  12.,  11.,  10.]),
 array([8, 7, 6, 5, 4, 3, 2, 1]))

In [62]:
# 4. Find indices of non-zero elements
# Write a function find_nonzero(x) that finds the indices of non-zero elements, with an API like
# return the indices of non-zero elements of an array.
# Use the function to get out the non-zero elements from an array containing the elements [1,2,0,0,4,0].

def find_nonzero(x):
    '''return the indices of non-zero elements of an array.
            Input:      x:  array
            Output:     indices: array of integer indices'''
    return np.where(x != 0)  # returning values of the array where x does not equal 0

arr = np.array([1, 2, 0, 0, 4, 0])

find_nonzero(arr) 

# why is dtype included in there???

(array([0, 1, 4], dtype=int64),)

In [66]:
# Use the function to get out the non-zero elements from an array containing the elements [1,2,0,0,4,0].
ar = np.array([arr[0], arr[1], arr[4]])
ar

array([1, 2, 4])

In [25]:
# 5. Array with random values
# Create a 3x3x3 array with normally distributed (μ=0,σ=1) random values.

nn = np.random.normal(0, 1, (3,3,3))

nn

array([[[-0.39476634, -1.34070308, -0.70830248],
        [ 1.91628257, -0.49862427, -0.330168  ],
        [ 0.70377306,  0.24722097,  0.40639419]],

       [[ 0.21158378, -1.32749904,  0.14563001],
        [-1.99830534,  0.9539513 , -0.80167597],
        [-0.20395343,  0.10290653, -1.42775928]],

       [[-0.48576105,  0.48079854,  0.3413549 ],
        [-0.18860345,  0.40625843, -0.86869269],
        [-0.7707751 ,  0.40036126, -1.11928535]]])

In [31]:
# 6. Operations on an array with random values
# Create a 10x10 array with random values. 
c = np.random.rand(10, 10)

# Find the minimum value of the 2nd row
imin = c.min(axis=1)[1]

# the maximum value of the 4th column
imax = c.max(axis=0)[3]

print(c)
imin, imax

[[ 0.70314396  0.30464616  0.32985507  0.7451876   0.6517311   0.03171564
   0.11791159  0.97237157  0.32831822  0.87775303]
 [ 0.97949089  0.05900012  0.65672037  0.0695323   0.26107575  0.24544717
   0.2119995   0.16116121  0.15629209  0.56744127]
 [ 0.83386577  0.86172433  0.37876309  0.92788615  0.42294854  0.47408268
   0.32660956  0.43478616  0.52158821  0.7661534 ]
 [ 0.99373541  0.27767679  0.78663835  0.93814906  0.21829142  0.05649356
   0.3814473   0.04252853  0.46389395  0.2314206 ]
 [ 0.20824616  0.37996093  0.77363547  0.66400589  0.21390754  0.91346854
   0.53014867  0.19437267  0.50949965  0.13961351]
 [ 0.2412728   0.4165327   0.0811405   0.3912988   0.63963851  0.97163445
   0.30341893  0.96920401  0.4251258   0.08465333]
 [ 0.85999962  0.89221644  0.41723994  0.68247554  0.88648066  0.06739458
   0.59418285  0.60408884  0.80651821  0.33483755]
 [ 0.80649436  0.1135646   0.29458946  0.04190382  0.96796918  0.93019242
   0.27127436  0.48845547  0.3398693   0.58410957]


(0.059000120858813787, 0.93814906389016683)

In [61]:
# 7. Vector without end points
# Create a vector of size 10 with values ranging from 0 to 1, both excluded.

d = np.linspace(0,1,12)[1:-1]
print(d.size)
d

10


array([ 0.09090909,  0.18181818,  0.27272727,  0.36363636,  0.45454545,
        0.54545455,  0.63636364,  0.72727273,  0.81818182,  0.90909091])

In [9]:
# 8. Sorted random vector¶
# Create a random vector of size 10, then sort it.

e = np.random.random(10)
print(e) # not sorted... random
e.sort()
e # sorted in order from least to greatest values

[ 0.47964158  0.77984781  0.46292221  0.57818183  0.36078354  0.61320948
  0.04623309  0.99418771  0.46175681  0.48144278]


array([ 0.04623309,  0.36078354,  0.46175681,  0.46292221,  0.47964158,
        0.48144278,  0.57818183,  0.61320948,  0.77984781,  0.99418771])

In [73]:
# 9. Test for array equality
# Write a function is_equal(A, B) that compare two arrays A and B and checks to see if they are equal.
# return True if two arrays are the same shape and all the elements are equal.

# The arrays count as equal if they are the same shape and all elements in the array are equal.

def is_equal(x,y):
    '''Inputs:
            A, B:  array
        Output:
            Bool:  True if A and B have the same shape and identical elements.'''
    return np.allclose(x,y) # returns True if two arrays are element-wise equal within a tolerance

# two random arrays of the same dimension that won't be equal most of the time
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# two equivalent arrays of the same dimension that will always be equal
A2 = np.array([[1., 2., 3.,], [4., 5., 6.]])
B2 = np.array([[1., 2., 3.,], [4., 5., 6.]])

# two differnet arrays of the same dimension that will never be equal
A3 = np.array([[1., 2., 3.,], [4., 5., 6.]])
B3 = np.array([[2., 4., 6.,], [8., 10., 12.]])

is_equal(A,B), is_equal(A2,B2), is_equal(A3,B3)

# ???

(False, True, False)

In [76]:
np.allclose?

In [77]:
# 10. Subtract the row mean from rows of a matrix
# Create a matrix. Then subtract the mean of each row of the matrix from the respective row. 
# Do this without using a loop (that is, using array operations).

f = np.array([[1., 2., 3.,], [4., 5., 6.]]) # my created matrix
g = f - f.mean(axis=1, keepdims=True) # the matrix with the mean of each row subtracted from the respective row.

print(f.mean(axis=1, keepdims=True))

g

[[ 2.]
 [ 5.]]


array([[-1.,  0.,  1.],
       [-1.,  0.,  1.]])

In [78]:
# 11. Multiply arrays
# Multiply an array of dimension (5,5,3) with an array with dimensions (5,5).
# Then multiply an array of dimension (3,5,5) with an array of dimension (5,5).

h = np.random.rand(5,5,3)  # a 3D array using random numbers
i = np.random.rand(5,5)    # a 2D array using random numbers

j = np.random.rand(3,5,5)  # a 3D array using random numbers

sol1 = h * i[:,:,None]     # element-by-element multiplication letting the 2D array act like a 3D array.
sol2 = j * i               # element-by-element multiplication letting the 2D array act like a 3D array.

sol1, sol2

(array([[[ 0.62499053,  0.54267979,  0.72375823],
         [ 0.00700739,  0.00641505,  0.00638919],
         [ 0.35182269,  0.40046287,  0.26844321],
         [ 0.54088323,  0.61791084,  0.0291968 ],
         [ 0.18691348,  0.08204574,  0.14861259]],
 
        [[ 0.36305962,  0.46564708,  0.59385707],
         [ 0.06703443,  0.17531507,  0.02397445],
         [ 0.3225547 ,  0.09876616,  0.25457282],
         [ 0.01380067,  0.00757773,  0.06346256],
         [ 0.08630194,  0.0233204 ,  0.07405421]],
 
        [[ 0.04275576,  0.07993199,  0.08078658],
         [ 0.01738489,  0.08109616,  0.15200544],
         [ 0.82694691,  0.67310392,  0.29149455],
         [ 0.2289436 ,  0.25164882,  0.6127883 ],
         [ 0.4117536 ,  0.3189016 ,  0.44600696]],
 
        [[ 0.2000628 ,  0.21587536,  0.44568431],
         [ 0.38804723,  0.07864629,  0.07509698],
         [ 0.88334201,  0.03537294,  0.20572941],
         [ 0.08986915,  0.33576515,  0.21729773],
         [ 0.17410762,  0.39927314,  0.36

In [90]:
# 12. Creating a new array
# Starting with an array
Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
Z

# Generate an array
# R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]].

# try to call each element (n) of the array and add +1, +2, +3, to each one... and make an array... [[n, n+1, n+2, n+3], ...]
k = np.array([]) 
for n in Z:
    if n<12:
        n = np.array([n,n+1,n+2,n+3])
        k.append(n)
    else:
        print(k)

type(k)


numpy.ndarray

In [110]:
# 13. Convert from Cartesian to polar coordinates¶
# Write a function cart2polar(xy) which takes in an Nx2 matrix of x, y pairs representing Cartesian coordinates and return
# the locations represented in polar coordinates in the same shape matrix. The API is
# Return equivalent polar coordinates of specified cartesian points.

xy = np.array([[1,2], [3,5], [2,7]])

def cart2pol(x):
    '''Inputs:
            xy: array
            Nx2 array of Cartesian coordinates, with columns x and y respectively.
        Returns:
            rp: array
            Nx2 array of polar coordinates, with columns radius and angle respectively'''
    
    rho = np.sqrt(x[:,0]**2 + x[:,1]**2)
    phi = np.arctan2(x[:,1], x[:,0]) 
    
    return(np.transpose(np.array([rho, phi])))

cart2pol(xy)

array([[ 2.23606798,  1.10714872],
       [ 5.83095189,  1.03037683],
       [ 7.28010989,  1.29249667]])

In [114]:
# 14. Compute and time for loops and array operations.
# Calculate the time it takes to do what we did in class
a = np.arange(1024.0).reshape(4, 8, 16, 2)   # a 4D array using sequential numbers
b = np.random.rand(4, 8, 16, 2)              # a 4D array using random numbers
sol = a * b  # element-by-element multiplication. This operation is about as fast as it can be on your computer.

# %time sol

# and the time required for doing the same operation with a series of 4 for loops, one for each dimension of the arrays. 
# Compare the times by calculating a ratio.

# n, k, j, i

sol2 = np.empty_like(sol)
for n in range(a.shape[0]):
    for k in range(a.shape[1]):
        for j in range(a.shape[2]):
            for i in range(a.shape[3]):

Wall time: 0 ns


array([[[[  0.00000000e+00,   1.81004492e-01],
         [  4.73546742e-01,   1.02206524e+00],
         [  3.10584584e-01,   4.68068097e+00],
         ..., 
         [  1.72275965e+01,   1.94082505e+01],
         [  2.45372305e+01,   1.93192833e+01],
         [  1.07161100e+01,   1.37695612e+01]],

        [[  1.89893757e+01,   1.47100434e-01],
         [  5.11033414e+00,   2.09979171e+01],
         [  1.88388417e+01,   1.74394050e+01],
         ..., 
         [  1.32561116e+01,   6.80916900e+00],
         [  8.46412530e+00,   5.78957289e+01],
         [  6.06290748e+01,   1.96743973e+01]],

        [[  4.23185159e+01,   1.67530864e+01],
         [  1.03402378e+01,   2.31407322e+01],
         [  1.75171718e+01,   3.94319373e+01],
         ..., 
         [  6.65228549e+01,   1.09180050e+01],
         [  6.13701608e+01,   2.96898600e+01],
         [  3.76634341e+01,   5.30825370e+01]],

        ..., 
        [[  1.11456481e+02,   3.65762116e+01],
         [  4.65688394e+01,   1.32187824e+

In [113]:
np.empty_like?

In [16]:
# 15. Fix the code
# This code needs to be fixed so that it can run properly and pass the assertion test at the bottom. 
# Write out what you changed to make it work and why it needed to be changed.

def calculate(a, b):
    """Do some calculations
    
    Take in two arrays, subtract 1/4 of the [:2,:] elements from the elements themselves.
    Then multiply with array b and return the result.
    
    Inputs:
        a: input array, shape [MxN]
        b: input array, shape [M]
    
    Returns:
        resultant array
    """

    aa = a[:2, :]
    aa /= 4.
    a[:2, :] -= aa

    return a*b
    

a = np.ones((3, 2)) 
b = np.ones(3)*3
res = calculate(a, b[:, None]) # I made the b array 2D so that I could multiply it with the 2D array a.

assert (res == np.array([[ 2.25,  2.25],[ 2.25,  2.25],[ 3., 3.]])).all()

# what does this asserstion error even mean?? What 'makes it true'???

AssertionError: 

In [ ]:
b

In [109]:
# 16. Calculate components of a vector
# Read in file data/burl1h2010.txt. This file gives a bunch of data from a wind station. In particular, read in the 
# wind direction, WDIR, and wind speed, WSPD. Then, write a function that calculates and returns the u and v components of this 
# wind vector, which point along the x- and y-axes.
# The function should have the following basic functionality:
# Take in vector and return components.

import math
data = np.loadtxt('burl1h2010.txt')

vdir = data[:,5]
vspd = data[:,6]

def wind_vec(vdir, vspd):
    '''Inputs:
        vdir: vector direction in degrees
        vspd: vector magnitude

    Returns:
        u: x component of vector
        v: y component of vector'''

    u = vspd*np.cos(np.radians(vdir))
    v = vspd*np.sin(np.radians(vdir))
    return([u],[v])

wind_vec(vdir, vspd)

([array([ -2.08397511,  -1.96070053,  -2.12119911, ...,  -9.56084447,
         -10.50707636,  -8.83345912])],
 [array([ 2.1580194 ,  3.01921404,  2.52794666, ...,  6.208885  ,
          5.5867116 ,  5.1       ])])

In [94]:
np.array

In [ ]:
# 17. (Grad) Write and use a class
# Consider one of the data files located in python4geosciences/data/MCH/. Write a class, dataclass, to store some of the 
# information in the file. The class should:
# be initialized with the name of the file (without file type suffix of .cnv2), and the temperature and salinity values 
# found in the file;
# contain a method, salt_mean, which returns the mean of the salinity;
# contain a method, temp_max, which returns the maximum value of the temperature values.
# Notice that there are many data files in this directory. It would be a lot of work to read them all in by hand. 
# Instead, write a loop which loops through the file names, reads in the necessary data, calls dataclass to store the 
# data in a class instance, and adds it to a list of all of the class instances. At the end of your solution, you should 
# have a list of all of the class instances, one for each data file.
# Hint: Check out the package glob for reading in file names with a wild card.

In [ ]:
# 18. (Grad) Running mean
# Write a function that computes averages using a sliding window over a vector; that is, it should take in a vector and for every 
# element in the vector, compute the average of that point with the N points on either side of the element. N should also be 
# an input parameter, and the function should return the original vector if N=0. The returned vector should be the same size 
# as the input vector.
# Do not use the pandas package or the function convolve; instead, use a loop. Use the following API for your function:
# Return the running average of a vector, with averaging window of size N.

# Inputs:
#     vec: Input vector
#     N (int): Averaging window size, or number of elements to include in mean on either side of each element.

# Outputs:
#     out: Vector of running-averaged values; same size as vec