In [ ]:
# Homework 03
# Due Tuesday, February 16th

In [2]:
# 1. Vector manipulation
# Create a vector of zeros of size 10 but have the fifth value be 1.

import numpy as np
a = np.zeros(10)
a[4] = 1

print(a)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


In [14]:
# 2. Vector range¶
# Create a vector with values ranging from 10 to 49, inclusive.

# import numpy as np
b = np.linspace(10.0,49.0,40.0)

print(b)

[ 10.  11.  12.  13.  14.  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.
  25.  26.  27.  28.  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.
  40.  41.  42.  43.  44.  45.  46.  47.  48.  49.]


In [20]:
# 3. Reverse a vector
# Write a function, reverse(x) which reverses a vector, so that the first element becomes the last element. The API should be
# return a 1D vector with the elements reversed

# Input
# -----
#     x: 1D array

# Output
# ------
#     res: 1D array, with the elements of `x` reversed

# Include this (or an equivalent description) in the function's docstring.

def reverse(x):      
    'Input ---- x:1D array'
    'Output ---- res: 1D array, with the elements of `x` reversed'
    return x[::-1]

x = np.linspace(10.0,20.0,11.0)
print(x)

reverse(x)

[ 10.  11.  12.  13.  14.  15.  16.  17.  18.  19.  20.]


array([ 20.,  19.,  18.,  17.,  16.,  15.,  14.,  13.,  12.,  11.,  10.])

In [9]:
# 4. Find indices of non-zero elements
# Write a function find_nonzero(x) that finds the indices of non-zero elements, with an API like
# return the indices of non-zero elements of an array.

# Input:      x:  array
# Output:     indices: array of integer indices

# Use the function to get out the non-zero elements from an array containing the elements [1,2,0,0,4,0].

def find_nonzero(x):
    return np.where(x != 0)

arr = [1,2,0,0,4,0]

find_nonzero(arr)

# ???

(array([0], dtype=int64),)

In [10]:
# 5. Array with random values
# Create a 3x3x3 array with normally distributed (μ=0,σ=1) random values.

b = np.random.rand(3, 3, 3)
print(b)

# don't know if this is "nornally distributed (μ=0,σ=1)"

[[[ 0.8956954   0.3512049   0.22924425]
  [ 0.88775031  0.06946026  0.03279106]
  [ 0.09192948  0.13772578  0.45343383]]

 [[ 0.97985689  0.24925947  0.07574758]
  [ 0.59794769  0.26705589  0.04758584]
  [ 0.82793036  0.02869034  0.54645134]]

 [[ 0.67332094  0.02799014  0.28186543]
  [ 0.60941261  0.51377413  0.49351721]
  [ 0.54937183  0.00765017  0.58438134]]]


In [33]:
# 6. Operations on an array with random values
# Create a 10x10 array with random values. 
c = np.random.rand(10, 10)
# or c = rand(10, 10, 10)
print(c)

# Find the minimum value of the 2nd row
imin = c.argmin(axis=1)
print(imin) #, c[imin])

# this doesn't seem to even work... and this is supposed to spit out the indices and values of the min values...


# the maximum value of the 4th column
imax = c.argmax(axis=1)
print(imax) #, c[imax], c.max())

[[ 0.36615845  0.24421801  0.98255147]
 [ 0.90522894  0.3751932   0.26438592]
 [ 0.73405554  0.00226101  0.86598361]]
[1 2 1]
[2 0 2]


In [39]:
# 7. Vector without end points
# Create a vector of size 10 with values ranging from 0 to 1, both excluded.

d = np.linspace(0,1,12,endpoint=True)[1:-1]
print(d)
d.size

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


10

In [41]:
# 8. Sorted random vector¶
# Create a random vector of size 10, then sort it.

e = np.random.random(10)
print(e) # not sorted... random
e.sort()
print(e) # sorted in order from least to greatest values

[ 0.40004503  0.19380074  0.35261718  0.51016843  0.3189525   0.25982189
  0.88936162  0.93499698  0.21744776  0.72903817]
[ 0.19380074  0.21744776  0.25982189  0.3189525   0.35261718  0.40004503
  0.51016843  0.72903817  0.88936162  0.93499698]


In [45]:
# 9. Test for array equality
# Write a function is_equal(A, B) that compare two arrays A and B and checks to see if they are equal.
# return True if two arrays are the same shape and all the elements are equal.

# Inputs:
#     A, B:  array
# Output:
#     Bool:  True if A and B have the same shape and identical elements.

# The arrays count as equal if they are the same shape and all elements in the array are equal.

def is_equal(x,y):
    return np.allclose(x,y)

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

is_equal(A,B)

False

In [44]:
# 9. Continued with equal arrays...

A2 = np.array([[1., 2., 3.,], [4., 5., 6.]])
B2 = np.array([[1., 2., 3.,], [4., 5., 6.]])

is_equal(A2,B2)

True

In [50]:
# 10. Subtract the row mean from rows of a matrix
# Create a matrix. Then subtract the mean of each row of the matrix from the respective row. 
# Do this without using a loop (that is, using array operations).

f = np.array([[1., 2., 3.,], [4., 5., 6.]])
g = f - f.mean(axis=1, keepdims=True)

print(f.mean(axis=1, keepdims=True))

g

[[ 2.]
 [ 5.]]


array([[-1.,  0.,  1.],
       [-1.,  0.,  1.]])

In [55]:
# 11. Multiply arrays
# Multiply an array of dimension (5,5,3) with an array with dimensions (5,5).
# Then multiply an array of dimension (3,5,5) with an array of dimension (5,5).
h = np.random.rand(5,5,3)  # a 3D array using random numbers
i = np.random.rand(5,5)    # a 2D array using random numbers

sol = h * i[:,:,None]      # element-by-element multiplication letting the 2D array act like a 3D array.
sol

array([[[  9.83698970e-02,   4.78625321e-01,   3.68648125e-02],
        [  6.90756560e-01,   5.33097921e-02,   2.11994519e-02],
        [  1.36290024e-01,   9.26474718e-02,   8.51271824e-02],
        [  3.88990641e-01,   9.15010594e-01,   8.18383793e-01],
        [  1.55124909e-02,   4.28152901e-01,   1.01540640e-04]],

       [[  5.70754105e-01,   4.85352055e-01,   5.64572030e-02],
        [  2.52032841e-01,   1.51557213e-01,   2.80256845e-01],
        [  4.49630122e-02,   2.21841353e-01,   1.38321707e-01],
        [  3.33964285e-01,   3.67362687e-02,   5.79269633e-01],
        [  3.90412956e-01,   2.95392878e-02,   5.05351050e-02]],

       [[  4.92002120e-01,   1.43915113e-02,   2.50908070e-01],
        [  1.50888176e-01,   1.10902910e-01,   2.42235371e-01],
        [  3.06655873e-02,   1.08396786e-02,   2.68809728e-02],
        [  2.16504511e-01,   3.00558671e-02,   2.99248631e-02],
        [  7.10987137e-01,   2.76884577e-01,   3.78885112e-01]],

       [[  8.12685450e-01,   6.644

In [ ]:
# 12. Creating a new array
# Starting with an array
# Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14].

# Generate an array
# R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]].

In [ ]:
# 13. Convert from Cartesian to polar coordinates¶
# Write a function cart2polar(xy) which takes in an Nx2 matrix of x, y pairs representing Cartesian coordinates and return
# the locations represented in polar coordinates in the same shape matrix. The API is
# Return equivalent polar coordinates of specified cartesian points.

# Inputs:
#     xy: array
#          Nx2 array of Cartesian coordinates, with columns x and y respectively.

# Returns:
#     rp: array
#         Nx2 array of polar coordinates, with columns radius and angle respectively

In [ ]:
# 14. Compute and time for loops and array operations.
# Calculate the time it takes to do what we did in class
# a = np.arange(1024.0).reshape(4, 8, 16, 2)   # a 4D array using sequential numbers
# b = np.random.rand(4, 8, 16, 2)              # a 4D array using random numbers
# sol = a * b  # element-by-element multiplication. This operation is about as fast as it can be on your computer.

# and the time required for doing the same operation with a series of 4 for loops, one for each dimension of the arrays. 
# Compare the times by calculating a ratio.

In [ ]:
# 15. Fix the code
# This code needs to be fixed so that it can run properly and pass the assertion test at the bottom. 
# Write out what you changed to make it work and why it needed to be changed.

def calculate(a, b):
    """Do some calculations
    
    Take in two arrays, subtract 1/4 of the [:2,:] elements from the elements themselves.
    Then multiply with array b and return the result.
    
    Inputs:
        a: input array, shape [MxN]
        b: input array, shape [M]
    
    Returns:
        resultant array
    """

    aa = a[:2, :]
    aa /= 4.
    a[:2, :] -= aa

    return a*b
    

a = np.ones((3, 2))
b = np.ones(3)*3
res = calculate(a, b)

assert (res == np.array([[ 2.25,  2.25],[ 2.25,  2.25],[ 3., 3.]])).all()

In [ ]:
# 16. Calculate components of a vector
# Read in file data/burl1h2010.txt. This file gives a bunch of data from a wind station. In particular, read in the wind direction, WDIR, and wind speed, WSPD. Then, write a function that calculates and returns the u and v components of this wind vector, which point along the x- and y-axes.
# The function should have the following basic functionality:
# Take in vector and return components.

# Inputs:
#     vdir: vector direction in degrees
#     vspd: vector magnitude

# Returns:
#     u: x component of vector
#     v: y component of vector

In [ ]:
# 17. (Grad) Write and use a class
# Consider one of the data files located in python4geosciences/data/MCH/. Write a class, dataclass, to store some of the 
# information in the file. The class should:
# be initialized with the name of the file (without file type suffix of .cnv2), and the temperature and salinity values 
# found in the file;
# contain a method, salt_mean, which returns the mean of the salinity;
# contain a method, temp_max, which returns the maximum value of the temperature values.
# Notice that there are many data files in this directory. It would be a lot of work to read them all in by hand. 
# Instead, write a loop which loops through the file names, reads in the necessary data, calls dataclass to store the 
# data in a class instance, and adds it to a list of all of the class instances. At the end of your solution, you should 
# have a list of all of the class instances, one for each data file.
# Hint: Check out the package glob for reading in file names with a wild card.

In [ ]:
# 18. (Grad) Running mean
# Write a function that computes averages using a sliding window over a vector; that is, it should take in a vector and for every 
# element in the vector, compute the average of that point with the N points on either side of the element. N should also be 
# an input parameter, and the function should return the original vector if N=0. The returned vector should be the same size 
# as the input vector.
# Do not use the pandas package or the function convolve; instead, use a loop. Use the following API for your function:
# Return the running average of a vector, with averaging window of size N.

# Inputs:
#     vec: Input vector
#     N (int): Averaging window size, or number of elements to include in mean on either side of each element.

# Outputs:
#     out: Vector of running-averaged values; same size as vec